# Generated by Django 5.1.5 on 2025-05-12 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_imge/'),
        ),
    ]
