# Generated by Django 5.1.5 on 2025-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_audio_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='featured_image',
            field=models.ImageField(blank=True, default='featured_image/default.png', null=True, upload_to='featured_image/'),
        ),
    ]
