# Generated by Django 5.1.5 on 2025-05-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_audio_artist_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.CharField(blank=True, default='memehive', max_length=200),
        ),
        migrations.AddField(
            model_name='audio',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
