# Generated by Django 5.1.5 on 2025-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_audio_album_audio_bitrate_audio_filesize_audio_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.CharField(blank=True, default='sound effects', max_length=100),
        ),
    ]
