# Generated by Django 5.1.5 on 2025-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_audio_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, default='www.memehive.net', max_length=255),
        ),
    ]
